version: "3.3"

services:
  main_server:
    image: nginx:latest
    depends_on:
      - frontend
      - backend
      - keycloak
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    depends_on:
      - library
      - keycloak
  library:
    restart: always
    image: sameersbn/postgresql:10-2
    environment:
      - PG_TRUST_LOCALNET=true
      - DB_NAME=evacc
      - DB_USER=admin
      - DB_PASS=admin123
      - PG_RUNDIR=/run/postgres
      - PG_LOGDIR=/var/log/postgres
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql
  keycloak:
    restart: always
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8080:8080"
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm-export.json"
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - DB_DATABASE=${KEYCLOAK_DATABASE_NAME}
      - DB_USER=${KEYCLOAK_DATABASE_USER}
      - DB_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
      - DB_ADDR=${KEYCLOAK_DATABASE_HOST}
      - DB_VENDOR=${KEYCLOAK_DATABASE_VENDOR}
    volumes:
      - ./realm-export.json:/opt/jboss/keycloak/realm-export.json
    depends_on:
      - keycloakdb
  keycloakdb:
    image: 'bitnami/mariadb:latest'
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=${KEYCLOAK_DATABASE_NAME}
      - MARIADB_USER=${KEYCLOAK_DATABASE_USER}
      - MARIADB_PASSWORD=${KEYCLOAK_DATABASE_PASSWORD}
    volumes:
      - keycloak-postgres:/var/lib/mysql
volumes:
  keycloak-postgres:
  data:
  logs:
